//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.PronosticoSoap")]
    public interface PronosticoSoap
    {
        
        // CODEGEN: Generating message contract since element name fecha from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerPronostico", ReplyAction="*")]
        ServiceReference1.ObtenerPronosticoResponse ObtenerPronostico(ServiceReference1.ObtenerPronosticoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerPronostico", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ObtenerPronosticoResponse> ObtenerPronosticoAsync(ServiceReference1.ObtenerPronosticoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPronosticoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPronostico", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ObtenerPronosticoRequestBody Body;
        
        public ObtenerPronosticoRequest()
        {
        }
        
        public ObtenerPronosticoRequest(ServiceReference1.ObtenerPronosticoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerPronosticoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string formato;
        
        public ObtenerPronosticoRequestBody()
        {
        }
        
        public ObtenerPronosticoRequestBody(string fecha, string formato)
        {
            this.fecha = fecha;
            this.formato = formato;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPronosticoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPronosticoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ObtenerPronosticoResponseBody Body;
        
        public ObtenerPronosticoResponse()
        {
        }
        
        public ObtenerPronosticoResponse(ServiceReference1.ObtenerPronosticoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerPronosticoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerPronosticoResult;
        
        public ObtenerPronosticoResponseBody()
        {
        }
        
        public ObtenerPronosticoResponseBody(string ObtenerPronosticoResult)
        {
            this.ObtenerPronosticoResult = ObtenerPronosticoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface PronosticoSoapChannel : ServiceReference1.PronosticoSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class PronosticoSoapClient : System.ServiceModel.ClientBase<ServiceReference1.PronosticoSoap>, ServiceReference1.PronosticoSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PronosticoSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PronosticoSoapClient.GetBindingForEndpoint(endpointConfiguration), PronosticoSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PronosticoSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PronosticoSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PronosticoSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PronosticoSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PronosticoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.ObtenerPronosticoResponse ServiceReference1.PronosticoSoap.ObtenerPronostico(ServiceReference1.ObtenerPronosticoRequest request)
        {
            return base.Channel.ObtenerPronostico(request);
        }
        
        public string ObtenerPronostico(string fecha, string formato)
        {
            ServiceReference1.ObtenerPronosticoRequest inValue = new ServiceReference1.ObtenerPronosticoRequest();
            inValue.Body = new ServiceReference1.ObtenerPronosticoRequestBody();
            inValue.Body.fecha = fecha;
            inValue.Body.formato = formato;
            ServiceReference1.ObtenerPronosticoResponse retVal = ((ServiceReference1.PronosticoSoap)(this)).ObtenerPronostico(inValue);
            return retVal.Body.ObtenerPronosticoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ObtenerPronosticoResponse> ServiceReference1.PronosticoSoap.ObtenerPronosticoAsync(ServiceReference1.ObtenerPronosticoRequest request)
        {
            return base.Channel.ObtenerPronosticoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ObtenerPronosticoResponse> ObtenerPronosticoAsync(string fecha, string formato)
        {
            ServiceReference1.ObtenerPronosticoRequest inValue = new ServiceReference1.ObtenerPronosticoRequest();
            inValue.Body = new ServiceReference1.ObtenerPronosticoRequestBody();
            inValue.Body.fecha = fecha;
            inValue.Body.formato = formato;
            return ((ServiceReference1.PronosticoSoap)(this)).ObtenerPronosticoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PronosticoSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PronosticoSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PronosticoSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:55572/Pronostico.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.PronosticoSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:55572/Pronostico.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PronosticoSoap,
            
            PronosticoSoap12,
        }
    }
}
